<?php

/**
 * @file
 * IndieWeb functionality.
 */

use Drupal\comment\CommentInterface;
use Drupal\comment\Entity\Comment;
use Drupal\comment\Entity\CommentType;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\indieweb\Entity\FeedInterface;
use Drupal\indieweb\Entity\WebmentionInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use IndieWeb\MentionClient;

define('WEBMENTION_QUEUE_NAME', 'indieweb_webmention');

/**
 * Implements hook_page_attachments_alter().
 */
function indieweb_page_attachments_alter(array &$attachments) {

  // Add webmention and pingback rel links.
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);
  if (!$is_admin) {

    $config = \Drupal::config('indieweb.webmention');
    if ($config->get('webmention_enable') && ($end_point = $config->get('webmention_endpoint'))) {
      $link = [
        '#tag' => 'link',
        '#attributes' => [
          'rel' => 'webmention',
          'href' => $end_point,
        ],
      ];
      $attachments['#attached']['html_head'][] = [$link, 'webmention'];
    }

    if ($config->get('pingback_enable') && ($end_point = $config->get('pingback_endpoint'))) {
      $link = [
        '#tag' => 'link',
        '#attributes' => [
          'rel' => 'pingback',
          'href' => $end_point,
        ],
      ];
      $attachments['#attached']['html_head'][] = [$link, 'pingback'];
    }
  }

  if (\Drupal::service('path.matcher')->isFrontPage()) {

    // IndieAuth Authentication endpoints.
    if (($config = \Drupal::config('indieweb.indieauth')) && ($config->get('enable')) && ($config->get('expose'))) {

      if ($end_point = $config->get('authorization_endpoint')) {
        $link = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'authorization_endpoint',
            'href' => $end_point,
          ],
        ];
        $attachments['#attached']['html_head'][] = [
          $link,
          'authorization_endpoint'
        ];
      }

      if ($end_point = $config->get('token_endpoint')) {
        $link = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'token_endpoint',
            'href' => $end_point,
          ],
        ];
        $attachments['#attached']['html_head'][] = [
          $link,
          'token_endpoint'
        ];
      }
    }

    // Micropub.
    if (($config = \Drupal::config('indieweb.micropub')) && ($config->get('micropub_enable')) && $config->get('micropub_add_header_link')) {

      $link = [
        '#tag' => 'link',
        '#attributes' => [
          'rel' => 'micropub',
          'href' => Url::fromRoute('indieweb.micropub.endpoint', [], ['absolute' => TRUE])
            ->toString(),
        ],
      ];

      $attachments['#attached']['html_head'][] = [
        $link,
        'micropub_endpoint'
      ];
    }

    // Microsub.
    if (($config = \Drupal::config('indieweb.microsub')) && $config->get('enable')) {

      $link = [
        '#tag' => 'link',
        '#attributes' => [
          'rel' => 'microsub',
          'href' => $config->get('microsub_endpoint'),
        ],
      ];

      $attachments['#attached']['html_head'][] = [
        $link,
        'microsub_endpoint'
      ];
    }

    // Feeds.
    /** @var \Drupal\indieweb\Entity\FeedInterface $feed */
    foreach (\Drupal::entityTypeManager()->getStorage('indieweb_feed')->loadMultiple() as $feed) {
      if ($feed->exposeRelHeaderLink()) {
        $link = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'feed',
            'href' => Url::fromUri('internal:/' . $feed->getPath(), ['absolute' => TRUE])->toString(),
          ],
        ];

        $attachments['#attached']['html_head'][] = [
          $link,
          'feed_endpoint_' . $feed->id(),
        ];

      }

      if ($feed->exposeJf2Feed() && $feed->exposeJf2HeaderLink()) {
        $link = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'alternate',
            'type' => 'application/jf2feed+json',
            'href' => Url::fromUri('internal:/' . str_replace('/', '-', $feed->getPath()) . '.jf2', ['absolute' => TRUE])->toString(),
          ],
        ];

        $attachments['#attached']['html_head'][] = [
          $link,
          'feed_endpoint_jf2_' . $feed->id(),
        ];

      }

    }
  }

}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 */
function indieweb_form_node_form_alter(&$form, FormStateInterface $form_state) {
  _indieweb_entity_form_alter($form, $form_state);
}

/**
 * Implements hook_entity_form_display_alter().
 */
function indieweb_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  if (_indieweb_user_authenticated_with_domain_on_edit_form()) {
    $form_display->removeComponent('account');
  }
}

/**
 * Checks if a user is authenticated with his domain on the user edit form.
 *
 * @return bool
 */
function _indieweb_user_authenticated_with_domain_on_edit_form() {
  $authenticated = FALSE;

  if (\Drupal::routeMatch()->getRouteName() == 'entity.user.edit_form' && ($account = \Drupal::routeMatch()->getParameter('user')) && \Drupal::currentUser()->id() == $account->id()) {
    // Check if login is enabled and current user is authenticated with domain
    // and has no administer users permission.
    if (\Drupal::config('indieweb.indieauth')->get('login_enable') && \Drupal::service('externalauth.authmap')->get($account->id(), 'indieweb') && !\Drupal::currentUser()->hasPermission('administer users')) {
      $authenticated = TRUE;
    }
  }

  return $authenticated;
}

/**
 * Helper function to add IndieWeb publish to fieldsets.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _indieweb_entity_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if ($entity) {
    $form['indieweb'] = [
      '#type' => 'details',
      '#title' => t('Publish to'),
      '#access' => \Drupal::currentUser()->hasPermission('send webmentions'),
      '#group' => 'advanced',
    ];

    $channels = indieweb_get_publishing_channels();
    $form['indieweb']['indieweb_publish_channels'] = [
      '#type' => 'checkboxes',
      '#options' => indieweb_get_publishing_channels(),
      '#default_value' => [],
      '#access' => !empty($channels),
    ];

    $options = [];
    $link_fields_string = \Drupal::config('indieweb.publish')->get('publish_link_fields');
    if (!empty($link_fields_string)) {
      $link_fields = explode('|', $link_fields_string);

      foreach ($link_fields as $field) {
        if ($entity->hasField($field)) {
          $options[$field] = t('Use @field', ['@field' => $field]);
        }
      }

      $form['indieweb']['indieweb_publish_link_field'] = [
        '#title' => t('Link field'),
        '#type' => 'select',
        '#access' => !empty($options),
        '#options' => ['' => ''] + $options,
        '#description' => t('Use the link from a field on this content.'),
      ];
    }

    // Comment webmention.
    if ($entity->getEntityTypeId() == 'comment' && ($reference_field = \Drupal::config('indieweb.publish')->get('publish_comment_webmention_field')) && $entity->hasField($reference_field) && !empty($options)) {
      /** @var \Drupal\comment\CommentInterface $comment */
      $comment = $entity;

      if (\Drupal::config('indieweb.publish')->get('publish_comment_permission_fields')) {
        $form[$reference_field]['#access'] = \Drupal::currentUser()->hasPermission('send webmentions');

        foreach (array_keys($options) as $field_name) {
          $form[$field_name]['#access'] = \Drupal::currentUser()->hasPermission('send webmentions');
        }
      }

      // Default values for link fields on comment.
      if (($parent = $comment->getParentComment()) && $parent->hasField($reference_field) && \Drupal::currentUser()->hasPermission('send webmentions')) {
        /** @var \Drupal\indieweb\Entity\WebmentionInterface $webmention */
        $webmention = $parent->get($reference_field)->entity;
        if ($webmention && $webmention->get('url')->value) {
          foreach ($options as $key => $field) {
            $form[$key]['widget'][0]['uri']['#default_value'] = $webmention->get('url')->value;
          }
        }
      }
    }

    if (\Drupal::config('indieweb.publish')->get('publish_custom_url')) {
      $form['indieweb']['indieweb_publish_custom_url'] = [
        '#type' => 'textfield',
        '#description' => t('Enter a custom URL'),
      ];
    }

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_indieweb_entity_content_form_submit';
      }
    }
  }

}

/**
 * Form submission handler for indieweb.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @see indieweb_form_node_form_alter()
 */
function _indieweb_entity_content_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if (method_exists($entity, 'isPublished') && $entity->isPublished()) {

    // Use our route for comments. Drupal core redirects to the entity, but we
    // need a page so webmentions can scan them for the content more easily.
    if ($entity->getEntityTypeId() == 'comment') {
      $source = Url::fromRoute('indieweb.comment.canonical', ['comment' => $entity->id()], ['absolute' => TRUE])->toString();
    }
    else {
      $source = $entity->toUrl()->setAbsolute(TRUE)->toString();
    }

    $publish_to = $form_state->getValue('indieweb_publish_channels');
    if (!empty($publish_to)) {
      foreach ($publish_to as $key => $value) {
        if ($key === $value) {
          indieweb_webmention_create_queue_item($source, $key, $entity->id(), $entity->getEntityTypeId());
        }
      }
    }

    // Link fields.
    $link_field = $form_state->getValue('indieweb_publish_link_field');
    if (!empty($link_field)) {
      if ($entity->hasField($link_field)) {
        $values = $entity->get($link_field)->getValue();
        if (!empty($values[0]['uri'])) {
          indieweb_webmention_create_queue_item($source, $values[0]['uri'], $entity->id(), $entity->getEntityTypeId());
        }
      }
    }

    // Custom URL.
    $custom_url = $form_state->getValue('indieweb_publish_custom_url');
    if (!empty($custom_url)) {
      indieweb_webmention_create_queue_item($source, $custom_url, $entity->id(), $entity->getEntityTypeId());
    }

  }
}

/**
 * Implements hook_entity_insert().
 */
function indieweb_entity_insert(EntityInterface $entity) {
  indieweb_entity_update($entity);
}

/**
 * Implements hook_entity_update().
 */
function indieweb_entity_update(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    try {
      _indieweb_entity_update_check_feeds($entity);
    }
    catch (Exception $ignored) {}
  }
}

/**
 * Implements hook_entity_delete().
 */
function indieweb_entity_delete(EntityInterface $entity) {

  if ($entity instanceof ContentEntityInterface) {

    // Delete from syndication table.
    \Drupal::database()
      ->delete('webmention_syndication')
      ->condition('entity_id', $entity->id())
      ->condition('entity_type_id', $entity->getEntityTypeId())
      ->execute();

    // Delete from feeds table.
    \Drupal::database()
      ->delete('indieweb_feed_items')
      ->condition('entity_id', $entity->id())
      ->condition('entity_type_id', $entity->getEntityTypeId())
      ->execute();

  }
}

/**
 * Update items for a feed.
 *
 * @param \Drupal\indieweb\Entity\FeedInterface $feed
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 * @throws \Exception
 */
function indieweb_update_feed_items(FeedInterface $feed) {
  \Drupal::database()
    ->delete('indieweb_feed_items')
    ->condition('feed', $feed->id())
    ->execute();

  foreach ($feed->getBundles() as $item) {
    list($entity_type, $bundle) = explode('|', $item);

    $entityType = \Drupal::entityTypeManager()->getDefinition($entity_type);
    $bundle_key = $entityType->getKey('bundle');

    $ids = \Drupal::entityQuery($entity_type)
      ->condition($bundle_key, $bundle)
      // TODO how safe is relying on created ?
      ->sort('created', 'DESC')
      ->condition('uid', $feed->getOwnerId())
      ->range(0, $feed->getLimit())
      ->execute();
    if (!empty($ids)) {
      foreach (\Drupal::entityTypeManager()->getStorage($entity_type)->loadMultiple($ids) as $entity) {
        _indieweb_entity_feed_insert($entity, $feed);
      }
    }
  }

  // Invalidate feed cache.
  Cache::invalidateTags(['indieweb_feed:' . $feed->id()]);
}

/**
 * Adds an entity to the feeds table, if necessary.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * @throws \Exception
 */
function _indieweb_entity_update_check_feeds(EntityInterface $entity) {
  /** @var \Drupal\indieweb\Entity\FeedInterface $feed */
  foreach (\Drupal::entityTypeManager()->getStorage('indieweb_feed')->loadMultiple() as $feed) {
    if (in_array($entity->getEntityTypeId() . '|' . $entity->bundle(), $feed->getBundles())) {
      _indieweb_entity_feed_insert($entity, $feed);
      Cache::invalidateTags(['indieweb_feed:' . $feed->id()]);
    }
  }
}

/**
 * Adds an entity to the feeds table.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\indieweb\Entity\FeedInterface|null $feed
 *
 * @throws \Exception
 */
function _indieweb_entity_feed_insert($entity, $feed) {
  // Assume yes if isPublished does not exist.
  $published = method_exists($entity, 'isPublished') ? $entity->isPublished() : 1;

  \Drupal::database()
    ->merge('indieweb_feed_items')
    ->key('entity_id', $entity->id())
    ->key('entity_type_id', $entity->getEntityTypeId())
    ->key('feed', $feed->id())
    ->fields([
      'published' => (int) $published,
      'timestamp' => $entity->getCreatedTime()
    ])
    ->execute();
}

/**
 * Implements hook_preprocess_node().
 */
function indieweb_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'full' || $variables['view_mode'] == 'teaser' || $variables['view_mode'] == 'indieweb_microformat') {

    // Add h-entry or h-event.
    $h_entry = FALSE;
    if (\Drupal::config('indieweb.microformats')->get('h_entry')) {
      $h_entry = TRUE;
    }
    if (($h_event = \Drupal::config('indieweb.microformats')->get('h_event')) && $variables['node']->bundle() == $h_event) {
      $h_entry = FALSE;
      $variables['attributes']['class'][] = 'h-event';
    }
    if ($h_entry) {
      $variables['attributes']['class'][] = 'h-entry';
    }

    if (\Drupal::config('indieweb.microformats')->get('post_metadata')) {
      $date = \Drupal::service('date.formatter')->format($variables['node']->getCreatedTime(), 'custom', 'c');

      $exclude_p_name_node_type = \Drupal::config('indieweb.microformats')->get('p_name_exclude_node_type');
      if ($exclude_p_name_node_type && $variables['node']->bundle() == $exclude_p_name_node_type) {
        $metadata = '<span class="hidden">
          <a href="' . $variables['node']->toUrl('canonical', ['absolute' => TRUE])->toString() . '" class="u-url">
            <span class="dt-published">' . $date . '</span>
          </a>
          <a href="/" class="u-author"></a>
        </span>
        ';
      }
      else {
        $metadata = '<span class="hidden">
          <a href="' . $variables['node']->toUrl('canonical', ['absolute' => TRUE])->toString() . '" class="u-url">
            <span class="p-name">' . $variables['node']->getTitle() . '</span>
            <span class="dt-published">' . $date . '</span>
          </a>
          <a href="/" class="u-author"></a>
        </span>';
      }

      /**
       * Rdf module might have set the 'metadata' key.
       *
       * Depending whether a patch is applied, or is in core, we need to make
       * sure we don't crash and/or overwrite this key.
       *
       * @see rdf_preprocess_node().
       * @see https://www.drupal.org/project/drupal/issues/2819695
       */
      if (isset($variables['metadata'])) {
        $other = $variables['metadata'];
        $variables['metadata'] = [];
        // Patch applied, or core has been updated already.
        if (is_array($other)) {
          $variables['metadata']['other'] = $other;
          $variables['metadata']['indieweb'] = ['#markup' => $metadata];
        }
        // The metadata has been rendered.
        else {
          $variables['metadata']['#markup'] = $other;
          $variables['metadata']['indieweb'] = ['#markup' => $metadata];
        }
      }
      else {
        $variables['metadata'] = ['#markup' => $metadata];
      }
    }
  }

}

/**
 * Implements hook_preprocess_comment().
 */
function indieweb_preprocess_comment(&$variables) {
  if ($variables['elements']['#view_mode'] == 'indieweb_microformat') {

    // h-entry
    if (\Drupal::config('indieweb.microformats')->get('h_entry_comment')) {
      $variables['attributes']['class'][] = 'h-entry';
    }

    // Post metadata.
    if (\Drupal::config('indieweb.microformats')->get('post_metadata_comment')) {
      $date = \Drupal::service('date.formatter')
        ->format($variables['elements']['#comment']->getCreatedTime(), 'custom', 'c');

      $metadata = '<span class="hidden">
        <a href="' . $variables['elements']['#comment']->toUrl('canonical', ['absolute' => TRUE])->toString() . '" class="u-url">
          <span class="dt-published">' . $date . '</span>
        </a>
        <a href="/" class="u-author"></a>
      </span>';

      // Attach it to content.
      $variables['content']['indieweb_medata_data']['#markup'] = $metadata;
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function indieweb_preprocess_field(&$variables) {

  // Put e-content on body.
  if ($variables['field_name'] == 'body' && \Drupal::config('indieweb.microformats')->get('e_content')) {
    $variables['attributes']['class'][] = 'e-content';

    // Check p-bridgy-twitter-content class. In case there is no summary field
    // on this entity or the field is empty, then add it.
    if (\Drupal::config('indieweb.microformats')->get('p_bridgy_twitter_content')) {

      $add = TRUE;
      /** @var \Drupal\Core\Entity\EntityInterface $entity */
      $entity = $variables['element']['#object'];
      $summary_fields = indieweb_get_summary_fields();
      foreach ($summary_fields as $field) {
        if ($entity->hasField($field) && $entity->get($field)->getValue()) {
          $add = FALSE;
        }
      }

      if ($add) {
        $variables['attributes']['class'][] = 'p-bridgy-twitter-content';
      }
    }
  }

  // Put e-content on comment_body.
  if ($variables['field_name'] == 'comment_body' && \Drupal::config('indieweb.microformats')->get('e_content_comment')) {
    $variables['attributes']['class'][] = 'e-content';
  }

  // Date range fields.
  if ($h_event = \Drupal::config('indieweb.microformats')->get('h_event')) {
    if ($variables['element']['#field_type'] == 'daterange' && $variables['element']['#object']->bundle() == $h_event && !empty($variables['items'][0]['content'])) {
      foreach ($variables['items'] as $key => $item) {
        if (isset($item['content']['start_date'])) {
          $variables['items'][$key]['content']['start_date']['#attributes']['class'][] = 'dt-start';
        }
        if (isset($item['content']['end_date'])) {
          $variables['items'][$key]['content']['end_date']['#attributes']['class'][] = 'dt-end';
        }
      }
    }
  }

  // In case there's a p-summary.
  if (in_array($variables['field_name'], indieweb_get_summary_fields())) {
    $variables['attributes']['class'][] = 'p-summary';

    if (\Drupal::config('indieweb.microformats')->get('p_bridgy_twitter_content')) {
      $variables['attributes']['class'][] = 'p-bridgy-twitter-content';
    }
  }

}

/**
 * Implements hook_preprocess_image_style().
 *
 * @param $variables
 */
function indieweb_preprocess_image_style(&$variables) {
  if (\Drupal::config('indieweb.microformats')->get('u_photo')) {
    $variables['image']['#attributes']['class'][] = 'u-photo';
  }
}

/**
 * Implements hook_preprocess_file_video().
 */
function indieweb_preprocess_file_video(&$variables) {
  if (\Drupal::config('indieweb.microformats')->get('u_video')) {
    if (!empty($variables['files'])) {
      foreach ($variables['files'] as $file) {
        $file['source_attributes']->addClass('u-video');
      }
    }
  }
}

/**
 * Implements hook_preprocess_file_entity_video().
 */
function indieweb_preprocess_file_entity_video(&$variables) {
  if (\Drupal::config('indieweb.microformats')->get('u_video')) {
    if (!empty($variables['files'])) {
      foreach ($variables['files'] as $file) {
        $file['source_attributes']->addClass('u-video');
      }
    }
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function indieweb_entity_extra_field_info() {
  $extra = [];

  $channels = indieweb_get_publishing_channels();
  if (!empty($channels)) {

    // Fields for node.
    if (\Drupal::moduleHandler()->moduleExists('node')) {
      foreach (NodeType::loadMultiple() as $bundle) {
        foreach ($channels as $url => $name) {
          $machine_name = indieweb_get_machine_name_from_url($url);
          $extra['node'][$bundle->id()]['display'][$machine_name] = [
            'label' => $name,
            'weight' => 0,
            'visible' => FALSE,
          ];
        }

        // Syndication field.
        $extra['node'][$bundle->id()]['display']['indieweb_syndication'] = [
          'label' => t('Syndication'),
          'weight' => 0,
          'visible' => FALSE,
        ];
      }
    }

    // Fields for comment.
    if (\Drupal::moduleHandler()->moduleExists('comment')) {
      foreach (CommentType::loadMultiple() as $bundle) {
        foreach ($channels as $url => $name) {
          $machine_name = indieweb_get_machine_name_from_url($url);
          $extra['comment'][$bundle->id()]['display'][$machine_name] = [
            'label' => $name,
            'weight' => 0,
            'visible' => FALSE,
          ];
        }

        // Syndication field.
        $extra['comment'][$bundle->id()]['display']['indieweb_syndication'] = [
          'label' => t('Syndication'),
          'weight' => 0,
          'visible' => FALSE,
        ];
      }
    }

  }


  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function indieweb_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display) {
  _indieweb_extra_fields_display($build, $node, $display);
}

/**
 * Implements hook_ENTITY_TYPE_view() for comment entities.
 */
function indieweb_comment_view(array &$build, CommentInterface $comment, EntityViewDisplayInterface $display) {
  _indieweb_extra_fields_display($build, $comment, $display);
}

/**
 * Renders extra fields like channels and syndication.
 *
 * @param array $build
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 */
function _indieweb_extra_fields_display(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Channel fields.
  $channels = indieweb_get_publishing_channels();
  if (!empty($channels)) {
    $back_link = '';
    $add_back_link = \Drupal::config('indieweb.publish')->get('back_link');
    if ($add_back_link == 'never') {
      $back_link = ' class="p-bridgy-omit-link" value="true"';
    }
    elseif ($add_back_link == 'maybe') {
      $back_link = ' class="p-bridgy-omit-link" value="maybe"';
    }
    foreach ($channels as $url => $name) {
      $machine_name = indieweb_get_machine_name_from_url($url);
      if ($display->getComponent($machine_name)) {
        $build[$machine_name] = [
          '#markup' => '<span class="hidden"><a href="' . $url . '"'. $back_link .'></a></span>',
        ];
      }
    }
  }

  // Syndication field.
  if ($display->getComponent('indieweb_syndication')) {
    $syndications = indieweb_get_syndications($entity->id(), $entity->getEntityTypeId());
    if ($syndications) {
      $items = [];

      foreach ($syndications as $url) {
        $items[] = [
          '#type' => 'link',
          '#url' => Url::fromUri($url),
          '#title' => $url,
          '#attributes' => [
            'class' => ['u-syndication']
          ]
        ];
      }

      $build['indieweb_syndication'] = [
        '#theme' => 'item_list',
        '#items' => $items,
        '#wrapper_attributes' => [
          'class' => ['indieweb-syndication-list'],
        ],
        '#title' => t('Syndications'),
      ];
    }
  }
}


/**
 * Implements hook_form_FORM_BASE_ID_alter() for the comments form.
 */
function indieweb_form_comment_form_alter(&$form, FormStateInterface $form_state) {
  _indieweb_entity_form_alter($form, $form_state);

  // Check the comment webmention reference field.
  $config = \Drupal::config('indieweb.comment');
  if ($config->get('comment_create_enable') && ($reference_field = $config->get('comment_create_webmention_reference_field'))) {
    if (isset($form[$reference_field]) && isset($form['comment_body'])) {
      /** @var \Drupal\comment\CommentInterface $comment */
      $comment = $form_state->getFormObject()->getEntity();
      // Deny access to comment form if webmention is referenced and body is
      // empty. Otherwise, you can not save this comment anymore.
      if (!$comment->isNew() && !empty($comment->get($reference_field)->target_id) && empty($comment->get('comment_body')->value)) {
        $form['comment_body']['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function indieweb_webmention_entity_insert(WebmentionInterface $webmention) {

  // Comment creation.
  if (($config = \Drupal::config('indieweb.comment')) && $config->get('comment_create_enable')) {

    // This can be simplified when config validation is ok
    if (
    !empty($config->get('comment_create_comment_type')) &&
    !empty($config->get('comment_create_webmention_reference_field')) &&
    !empty($config->get('comment_create_node_comment_field')) &&
    $webmention->get('property')->value == 'in-reply-to' &&
    !empty($webmention->get('content_text')->value)) {

      $pid = 0;
      $path = \Drupal::service('path.alias_manager')->getPathByAlias($webmention->get('target')->value);
      try {
        $params = Url::fromUri("internal:" . $path)->getRouteParameters();

        // This can be a reply on a comment. Get the node then to attach the
        // comment there and set pid.
        if (key($params) == 'comment') {
          /** @var \Drupal\comment\CommentInterface $comment */
          $comment = \Drupal::entityTypeManager()->getStorage('comment')->load($params['comment']);
          if ($comment && $comment->getCommentedEntityTypeId() == 'node') {
            $pid = $comment->id();
            $params = ['node' => $comment->getCommentedEntityId()];
          }
        }

        // We currently support only comments on nodes.
        if (!empty($params) && key($params) == 'node') {
          $entity_type = key($params);

          $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
          if ($storage) {

            $comment_type = $config->get('comment_create_comment_type');
            $comment_comment_webmention_field_name = $config->get('comment_create_webmention_reference_field');
            $comment_node_comment_field_name = $config->get('comment_create_node_comment_field');

            /** @var \Drupal\node\NodeInterface $node */
            $node = $storage->load($params[$entity_type]);
            if ($node && $node->hasField($comment_node_comment_field_name) && $node->{$comment_node_comment_field_name}->status == 2) {

              // Last check now is to make sure we do not create the same
              // comment again.
              if (indieweb_source_exists_as_syndication($webmention)) {
                return;
              }

              $subject = 'Auto created comment from webmention';

              $values = [
                'subject' => $subject,
                'status' => $config->get('comment_create_default_status'),
                'entity_id' => $node->id(),
                'entity_type' => 'node',
                'pid' => $pid,
                'comment_type' => $comment_type,
                'field_name' => $comment_node_comment_field_name,
                $comment_comment_webmention_field_name => [
                  'target_id' => $webmention->id(),
                ]
              ];

              // Match authors if possible.
              $authors = Settings::get('indieweb_comment_authors', []);
              $author_name = $webmention->get('author_name')->value;
              $values['name'] = $author_name;
              if (isset($authors[$author_name])) {
                $values['uid'] = $authors[$author_name];
              }

              $comment = Comment::create($values);
              $comment->save();

              // Send mail notification.
              if ($config->get('comment_create_mail_notification')) {
                $mailManager = \Drupal::service('plugin.manager.mail');
                $module = 'indieweb';
                $key = 'webmention_comment_created';
                $to = $config->get('comment_create_mail_notification');
                $params['comment'] = $comment;
                $params['comment_webmention_body'] = $webmention->get('content_text')->value;
                $langcode = \Drupal::currentUser()->getPreferredLangcode();
                $mailManager->mail($module, $key, $to, $langcode, $params, NULL);
              }
            }
          }
        }
      }
      catch (Exception $e) {
        \Drupal::logger('indieweb_comment')->notice('Failed to create a comment: @message', ['@message' => $e->getMessage()]);
      }
    }

  }

}

/**
 * Implements hook_mail.
 *
 * @param $key
 * @param $message
 * @param $params
 */
function indieweb_mail($key, &$message, $params) {

  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'webmention_comment_created':
      /** @var \Drupal\comment\CommentInterface $comment */
      $comment = $params['comment'];
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Comment created on "@title" via webmention', array('@title' => $comment->getCommentedEntity()->label()), $options);
      $message['body'][] = $params['comment_webmention_body'];
      if (!$comment->isPublished()) {
        $message['body'][] = "---------------------\n" . t('The comment is unpublished, so check the approval queue at @url', ['@url' => Url::fromRoute('comment.admin_approval', [], ['absolute' => TRUE])->toString()]);
      }
      break;
  }
}


/**
 * Implements hook_cron().
 */
function indieweb_cron() {
  if (\Drupal::config('indieweb.publish')->get('publish_send_webmention_by') == 'cron') {
    indieweb_handle_webmention_queue();
  }
}

/**
 * Get the syndications for an entity.
 *
 * @param $entity_id
 * @param $entity_type_id
 *
 * @return array
 */
function indieweb_get_syndications($entity_id, $entity_type_id) {
  $syndications = [];

  $records = \Drupal::database()->query('SELECT url FROM {webmention_syndication} WHERE entity_id = :entity_id AND entity_type_id = :entity_type_id', [':entity_id' => $entity_id, ':entity_type_id' => $entity_type_id]);
  foreach ($records as $record) {
    $syndications[] = $record->url;
  }

  return $syndications;
}

/**
 * Returns the publishing channels.
 *
 * @return array
 */
function indieweb_get_publishing_channels() {
  $channels = [];
  $config = \Drupal::config('indieweb.publish')->get('channels');
  if (!empty($config)) {
    $lines = explode("\n", $config);
    foreach ($lines as $line) {
      $line = trim($line);
      if (!empty($line)) {
        $name_url = explode('|', $line);
        if (!empty($name_url[0]) && !empty($name_url[1])) {
          $channels[$name_url[1]] = $name_url[0];
        }
      }
    }
  }

  return $channels;
}

/**
 * Creates a webmention queue item.
 *
 * @param $source
 * @param $target
 * @param $entity_id
 * @param $entity_type_id
 */
function indieweb_webmention_create_queue_item($source, $target, $entity_id = '', $entity_type_id = '') {
  $data = [
    'source' => $source,
    'target' => $target,
    'entity_id' => $entity_id,
    'entity_type_id' => $entity_type_id
  ];

  // Bail out when target is one of the silos, but not actually the webmention
  // endpoint. This can happen with reply urls to twitter for example.
  if (indieweb_is_silo_url($target)) {
    return;
  }

  try {
    \Drupal::queue(WEBMENTION_QUEUE_NAME)->createItem($data);
  }
  catch (\Exception $e) {
    \Drupal::logger('indieweb_queue')->notice('Error creating queue item: @message', ['@message' => $e->getMessage()]);
  }

}

/**
 * Handles the webmention queue.
 */
function indieweb_handle_webmention_queue() {
  $end = time() + 15;
  $channels = indieweb_get_publishing_channels();
  while (time() < $end && ($item = \Drupal::queue(WEBMENTION_QUEUE_NAME)->claimItem())) {
    $data = $item->data;
    if (!empty($data['source']) && !empty($data['target'])) {
      $sourceURL = $data['source'];
      $targetURL = $data['target'];
      $client = new MentionClient();

      try {
        $response = $client->sendWebmention($sourceURL, $targetURL);

        // Store the syndication when the targetUrl is in the channels.
        if (isset($channels[$targetURL])) {
          if (!empty($response) && $response['code'] == 201 && !empty($response['headers']['Location'])) {

            if (!empty($data['entity_id']) && !empty($data['entity_type_id'])) {
              $values = [
                'entity_id' => $data['entity_id'],
                'entity_type_id' => $data['entity_type_id'],
                'url' => $response['headers']['Location']
              ];

              \Drupal::database()
                ->insert('webmention_syndication')
                ->fields($values)
                ->execute();

              Cache::invalidateTags([$data['entity_type_id'] . ':' . $data['entity_id']]);
            }

            // Log the response if configured.
            if (\Drupal::config('indieweb.publish')->get('publish_log_response')) {
              \Drupal::logger('indieweb_publish_response')->notice('response for @source to @target: @response', ['@response' => print_r($response, 1), '@source' => $sourceURL, '@target' => $targetURL]);
            }

          }
          else {
            if (\Drupal::config('indieweb.publish')->get('publish_log_response')) {
              \Drupal::logger('indieweb_publish')->notice('No 201 or location received when publishing for @source to @target: @response', ['@response' => print_r($response, 1), '@source' => $sourceURL, '@target' => $targetURL]);
            }
          }
        }

      }
      catch (Exception $e) {
        \Drupal::logger('indieweb_publish')->notice('Error sending webmention for @source to @target: @message', ['@message' => $e->getMessage(), '@source' => $sourceURL, '@target' => $targetURL]);
      }
    }

    // Store in send table.
    $values = [
      'source' => $data['source'],
      'target' => $data['target'],
      'entity_id' => !empty($data['entity_id']) ? $data['entity_id'] : 0,
      'entity_type_id' => !empty($data['entity_type_id']) ? $data['entity_type_id'] : '',
      'created' => \Drupal::time()->getCurrentTime(),
    ];

    try {
      \Drupal::database()
        ->insert('webmention_send')
        ->fields($values)
        ->execute();
    }
    catch (\Exception $e) {
      \Drupal::logger('indieweb_publish')->notice('Error saving send webmention record: @message', ['@message' => $e->getMessage()]);
    }

    // Remove the item - always.
    \Drupal::queue(WEBMENTION_QUEUE_NAME)->deleteItem($item);
  }
}

/**
 * Sanitizes a url to use as a machine name.
 *
 * @param $url
 *
 * @return string
 */
function indieweb_get_machine_name_from_url($url) {
  return 'indieweb_' . str_replace(['https://', 'http://', '/', '-', '.'], '', $url);
}

/**
 * Get summary fields for microformats.
 *
 * @return array
 */
function indieweb_get_summary_fields() {
  static $fields = [];
  static $loaded = FALSE;

  if (!$loaded) {
    $loaded = TRUE;
    $fields = explode("\n", \Drupal::config('indieweb.microformats')->get('p_summary'));
  }

  return $fields;
}

/**
 * Checks if a source url already exists as syndication.
 *
 * This can happen when you reply from your site to twitter. Brid.gy will then
 * send that reply on  twitter back as a webmention.
 *
 * @param \Drupal\indieweb\Entity\WebmentionInterface $webmention
 *
 * @return bool
 */
function indieweb_source_exists_as_syndication(WebmentionInterface $webmention) {
  $exists = FALSE;

  if (strpos($webmention->get('source')->value, 'brid-gy.appspot') !== FALSE) {
    $parts = parse_url($webmention->get('source')->value);
    $path_parts = explode('/', $parts['path']);
    if (!empty($path_parts[5])) {
      $exists = \Drupal::database()->query("SELECT count(url) as count FROM {webmention_syndication} WHERE url LIKE :id", [':id' => '%/' . db_like($path_parts[5])])->fetchField();
    }
  }

  return $exists;
}

/**
 * Checks whether the url is a silo URL or not. Currently detects Twitter urls.
 *
 * e.g. https://twitter.com/studioemma/status/999193968234713093 should be
 * marked as a silo url.
 *
 * @param $url
 *
 * @return bool
 */
function indieweb_is_silo_url($url) {
  $is_silo_url = FALSE;

  if (strpos($url, 'twitter.com') !== FALSE) {
    $is_silo_url = TRUE;
  }

  return $is_silo_url;
}
