# schema for indieweb_webmention.comment
indieweb_webmention.comment:
  type: config_object
  label: 'Indieweb comments'
  mapping:
    comment_create_enable:
      type: boolean
      label: 'Enable comment support'
    comment_create_default_status:
      type: integer
      label: 'Default status of a new comment'
    comment_create_comment_type:
      type: string
      label: 'The comment type'
    comment_create_webmention_reference_field:
      type: string
      label: 'The webmention reference field on the comment type'
    comment_create_node_comment_field:
      type: string
      label: 'The comment field on the node type'
    comment_create_mail_notification:
      type: email
      label: 'Send mail notification'
    comment_create_whitelist_domains:
      type: 'string'
      label: 'Automatically approve webmention comments from these domains'

# schema for indieweb_webmention.settings
indieweb_webmention.settings:
  type: config_object
  label: 'Indieweb webmention'
  mapping:
    webmention_endpoint:
      type: string
      label: 'Webmention endpoint'
    webmention_notify:
      type: boolean
      label: 'Whether to enable the notify endpoint'
    webmention_secret:
      type: string
      label: 'Webmention secret'
    webmention_internal:
      type: boolean
      label: 'Whether to use the internal endpoint'
    webmention_internal_handler:
      type: 'string'
      label: 'Internal handler to process the webmention'
    webmention_content_domain:
      type: 'string'
      label: 'The domain where the content is served'
    webmention_log_processing:
      type: boolean
      label: 'Whether to log the processing of received webmentions'
    webmention_detect_identical:
      type: boolean
      label: 'Whether to detect identical webmentions and not store them'
    webmention_expose_link_tag:
      type: boolean
      label: 'Whether to expose the webmention link tag'
    webmention_expose_link_header:
      type: boolean
      label: 'Whether to expose the webmention link header'
    blocked_domains:
      type: 'string'
      label: 'Block domains for incoming webmentions or pingbacks'
    pingback_internal:
      type: boolean
      label: 'Whether to use the internal pingback endpoint'
    pingback_expose_link_tag:
      type: boolean
      label: 'Whether to expose the pingback link tag'
    pingback_expose_link_header:
      type: boolean
      label: 'Whether to expose the pingback header link'
    pingback_notify:
      type: boolean
      label: 'Whether to use the notification pingback endpoint'
    pingback_endpoint:
      type: string
      label: 'Pingback endpoint'
    webmention_uid:
      type: integer
      label: 'The user id of the article'
    webmention_log_payload:
      type: boolean
      label: 'Whether to log the payload'
    syndication_targets:
      type: text
      label: 'Channels to publish to'
    bridgy_back_link:
      type: string
      label: 'How to handle Bridgy back links'
    send_custom_url:
      type: boolean
      label: 'Expose dynamic URL textfield'
    send_link_fields:
      type: string
      label: 'Fields to use'
    send_webmention_handler:
      type: string
      label: 'How to handle the webmention send queue'
    send_log_response:
      type: boolean
      label: 'Whether to log the response of the publish call'
    send_comment_webmention_field:
      type: string
      label: 'The comment webmention field'
    send_comment_permission_fields:
      type: boolean
      label: 'Put fields under permission'

# schema for webmention_delete_action
action.configuration.webmention_delete_action:
  type: action_configuration_default
  label: 'Delete webmention'

# schema for comment_reset_thread
action.configuration.comment_reset_thread:
  type: action_configuration_default
  label: 'Reset comment thread'

# schema for entity_reference_webmention setting
field.formatter.settings.entity_reference_webmention:
  type: mapping
  label: 'Webmention format settings'
  mapping:
    show_avatar:
      type: integer
      label: 'Show avatar'
    show_summary:
      type: boolean
      label: 'Show summary'
    show_photo:
      type: boolean
      label: 'Show photo'
    show_created:
      type: boolean
      label: 'Show created'
    replace_comment_user_picture:
      type: string
      label: 'Replace comment user picture'
