<?php

/**
 * @file
 * IndieWeb Microsub module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_page_attachments_alter().
 */
function indieweb_microsub_page_attachments_alter(array &$attachments) {

  if (\Drupal::service('path.matcher')->isFrontPage()) {

    if (($config = \Drupal::config('indieweb_microsub.settings')) && $config->get('microsub_expose_link_tag')) {

      if ($config->get('microsub_internal')) {
        $endpoint = Url::fromRoute('indieweb.microsub.endpoint', [], ['absolute' => TRUE])->toString();
      }
      else {
        $endpoint = $config->get('microsub_endpoint');
      }

      $link = [
        '#tag' => 'link',
        '#attributes' => [
          'rel' => 'microsub',
          'href' => $endpoint,
        ],
      ];

      $attachments['#attached']['html_head'][] = [$link, 'microsub_endpoint'];
    }
  }

}

/**
 * Implements hook_cron().
 */
function indieweb_microsub_cron() {

  if (\Drupal::config('indieweb_microsub.settings')->get('microsub_internal') &&
    \Drupal::config('indieweb_microsub.settings')->get('microsub_internal_handler') == 'cron') {
    \Drupal::service('indieweb.microsub.client')->fetchItems();
  }

}

/**
 * Implements hook_indieweb_websub_subscribe().
 */
function indieweb_microsub_indieweb_websub_subscribe($url, $seconds) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    if (!$seconds) {
      $seconds = 86400 * 7;
    }
    $source->setNextFetch(\Drupal::time()->getRequestTime() + $seconds);
    $source->set('websub', 1);
    $source->save();
    return TRUE;
  }

  return NULL;
}

/**
 * Implements hook_indieweb_websub_unsubscribe().
 */
function indieweb_microsub_indieweb_websub_unsubscribe($url) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    $source->setNextFetch(0);
    $source->set('websub', 0);
    $source->save();
    return TRUE;
  }

  return NULL;
}

/**
 * Implements hook_indieweb_websub_notification().
 */
function indieweb_microsub_indieweb_websub_notification($url, $hub, $content) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    \Drupal::service('indieweb.microsub.client')->fetchItems($source->label(), $content);
  }
}
