<?php

/**
 * @file
 * IndieWeb Microsub module.
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments_alter().
 */
function indieweb_microsub_page_attachments_alter(array &$attachments) {

  if (\Drupal::service('path.matcher')->isFrontPage()) {

    if (($config = \Drupal::config('indieweb_microsub.settings')) && ($config->get('microsub_expose_link_tag') || $config->get('microsub_expose_link_header'))) {

      if ($config->get('microsub_internal')) {
        $endpoint = Url::fromRoute('indieweb.microsub.endpoint', [], ['absolute' => TRUE])->toString();
      }
      else {
        $endpoint = $config->get('microsub_endpoint');
      }

      if ($config->get('microsub_expose_link_header')) {
        $attachments['#attached']['http_header'][] = ['Link', '<' . $endpoint . '>; rel="microsub"'];
      }

      if ($config->get('microsub_expose_link_tag')) {
        $link = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'microsub',
            'href' => $endpoint,
          ],
        ];
        $attachments['#attached']['html_head'][] = [$link, 'microsub_endpoint'];
      }

    }
  }

}

/**
 * Implements hook_cron().
 */
function indieweb_microsub_cron() {

  if (\Drupal::config('indieweb_microsub.settings')->get('microsub_internal') &&
    \Drupal::config('indieweb_microsub.settings')->get('microsub_internal_handler') == 'cron') {
    \Drupal::service('indieweb.microsub.client')->fetchItems();
  }

}

/**
 * Implements hook_indieweb_websub_subscribe().
 */
function indieweb_microsub_indieweb_websub_subscribe($url, $seconds) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    if (!$seconds) {
      $seconds = 86400 * 7;
    }
    $source->setNextFetch(\Drupal::time()->getRequestTime() + $seconds);
    $source->set('websub', 1);
    $source->save();
    return TRUE;
  }

  return NULL;
}

/**
 * Implements hook_indieweb_websub_unsubscribe().
 */
function indieweb_microsub_indieweb_websub_unsubscribe($url) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    $source->setNextFetch(0);
    $source->set('websub', 0);
    $source->save();
    return TRUE;
  }

  return NULL;
}

/**
 * Implements hook_indieweb_websub_notification().
 */
function indieweb_microsub_indieweb_websub_notification($url, $content) {
  /** @var \Drupal\indieweb_microsub\Entity\MicrosubSourceInterface[] $sources */
  $sources = \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->loadByProperties(['url' => $url]);
  if ($sources) {
    $source = array_shift($sources);
    \Drupal::service('indieweb.microsub.client')->fetchItems($source->label(), $content);
  }
}

/**
 * Implements hook_indieweb_websub_needs_resubscribe().
 */
function indieweb_microsub_indieweb_websub_needs_resubscribe() {
  return \Drupal::entityTypeManager()->getStorage('indieweb_microsub_source')->getSourcesToResubscribe();
}

/**
 * Returns the default user agent when calling feeds.
 *
 * @return mixed|null
 */
function indieweb_microsub_http_client_user_agent() {
  return Settings::get('indieweb_microsub_http_client_user_agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36');
}
