<?php

/**
 * @file
 * IndieWeb IndieAuth module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments_alter().
 */
function indieweb_indieauth_page_attachments_alter(array &$attachments) {

  if (\Drupal::service('path.matcher')->isFrontPage()) {

    if (($config = \Drupal::config('indieweb_indieauth.settings')) && ($config->get('expose_link_tag') || $config->get('expose_link_header'))) {

      if ($config->get('auth_internal')) {
        $authorization_endpoint = Url::fromRoute('indieweb.indieauth.auth', [], ['absolute' => TRUE])->toString();
        $token_endpoint = Url::fromRoute('indieweb.indieauth.token', [], ['absolute' => TRUE])->toString();
      }
      else {
        $authorization_endpoint = $config->get('authorization_endpoint');
        $token_endpoint = $config->get('token_endpoint');
      }

      if ($config->get('expose_link_header')) {
        $attachments['#attached']['http_header'][] = ['Link', '<' . $authorization_endpoint . '>; rel="authorization_endpoint"'];
        $attachments['#attached']['http_header'][] = ['Link', '<' . $token_endpoint . '>; rel="token_endpoint"'];
      }

      if ($config->get('expose_link_tag')) {

        $link_authorization = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'authorization_endpoint',
            'href' => $authorization_endpoint,
          ],
        ];

        $link_token = [
          '#tag' => 'link',
          '#attributes' => [
            'rel' => 'token_endpoint',
            'href' => $token_endpoint,
          ],
        ];

        $attachments['#attached']['html_head'][] = [$link_authorization, 'authorization_endpoint'];
        $attachments['#attached']['html_head'][] = [$link_token, 'token_endpoint'];
      }

    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function indieweb_indieauth_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (indieweb_indieauth_user_authenticated_with_domain_on_edit_form()) {

    // Hide password fields as it's not needed. We also hide the current pass
    // so that the e-mail can be changed.
    $form['account']['pass']['#access'] = FALSE;
    $form['account']['current_pass']['#access'] = FALSE;

    // Set user_pass_reset in form_state. Users can always change their email
    // if wanted. The unique validation constraint will make sure they can not
    // set it to an existing email.
    $form_state->set('user_pass_reset', 1);
  }
}

/**
 * Checks if a user is authenticated with his domain on the user edit form.
 *
 * @return bool
 */
function indieweb_indieauth_user_authenticated_with_domain_on_edit_form() {
  if (\Drupal::routeMatch()->getRouteName() != 'entity.user.edit_form') {
    return FALSE;
  }
  $account = \Drupal::routeMatch()->getParameter('user');
  if (\Drupal::currentUser()->id() != $account->id()) {
    return FALSE;
  }

  // Check if login is enabled.
  if (!\Drupal::config('indieweb_indieauth.settings')->get('login_enable')) {
    return FALSE;
  }

  // If the user has the administer user permission we do not care on the edit
  // form how they are authenticated, we should leave it alone.
  if (\Drupal::currentUser()->hasPermission('administer users')) {
    return FALSE;
  }

  // Check if the user was authenticated with their domain through IndieAuth.
  $externalAuthMapId = 'externalauth.authmap';
  if (\Drupal::hasService($externalAuthMapId)) {
    /** @var \Drupal\externalauth\AuthmapInterface $externalAuthMap */
    $externalAuthMap = \Drupal::service($externalAuthMapId);
    $externalAuthMap->get($account->id(), 'indieweb');
  }

  return FALSE;
}
